### ISSUE TITLE
Plans for new version to use OWL-API 5.1.16

### ISSUE THREAD

**Issue by rlbns** [owlcs/ont-api#19]
There is a fix in OWL-API 5.1.16 that our project needs. We are currently using ONT-API 2.0.0 and appreciate the integration with Jena. Are there plans to create a new version of ONT-API that pulls in the latest OWL-API? It looks like Jena also has a more recent release.

Thanks for supporting this library.

**Comment by sszuev** [comment]
Hello.

1) yes, there are plans for new release (~ this autumn maybe), but i'm not sure about OWL-API 5.1.16.
I can't switch to 5.1.16 since there is a bug in that release - https://github.com/owlcs/owlapi/issues/951 - which leads to tests failures.  Although this error is not critical, to change dependencies I need disable these (acceptance though) tests first, which I don't want to do for obvious reasons.

2) But this is about tests. A library itself depends only on OWL-API-api, no other OWL-API modules are involved. 
OWL-API-api(v5) has not changed over the years. So you can easily use ONTAPI with whatever version of OWL-API(v5), just use `exclusion` maven  instruction, e.g.:


        <dependency>
            <groupId>com.github.owlcs</groupId>
            <artifactId>ontapi</artifactId>
            <version>2.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>net.sourceforge.owlapi</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-distribution</artifactId>
            <version>5.1.16</version>
        </dependency>

**Comment by rlbns** [comment]
This approach worked nicely - great to know it's safe to mix versions like that.

Thanks for the quick response!
